### ISSUE TITLE
Flock 0.3.2 is incompatible with base 4.15

### ISSUE THREAD

**Issue by gregorias** [hesselink/flock#15]
[Base 4.15](https://hackage.haskell.org/package/base) came out this year, could you update flock's bound to allow for it? 

The current bounds (<4.15) cause the package to fail when I use nightly stackage (ghc 9.0).

**Comment by hesselink** [comment]
Tested and published a new revision to allow base 4.15

**Comment by gregorias** [comment]
Thank you
