### ISSUE TITLE
Inaccurate version bounds in  .cabal file

### ISSUE THREAD

**Issue by hvr** [hesselink/flock#6]
Specifically, `throwErrnoPathIfMinus1Retry_` wasn't exported by `System.Posix.Error` before `unix-2.5.0.0`, and compilation fails with e.g. `unix-2.4.2.0`:

```
[1 of 1] Compiling System.Lock.FLock ( dist/dist-sandbox-69b443ad/build/System/Lock/FLock.hs, dist/dist-sandbox-69b443ad/build/System/Lock/FLock.o )

System/Lock/FLock.hsc:26:38:
    Module
    `System.Posix.Error'
    does not export
    `throwErrnoPathIfMinus1Retry_'
```

**Comment by hesselink** [comment]
Thanks, I see you've already updated the bounds on hackage. I've restricted the version in the repo as well for now, I'll see if I can support the older version as well later.

**Comment by hvr** [comment]
@hesselink oh and btw, `flock` currently doesn't have an install-plan on GHC8:

http://matrix.hackage.haskell.org/package/flock

**Comment by hesselink** [comment]
Yeah, it's on my list :) Thanks!

**Comment by hesselink** [comment]
I was about to try and fix these old versions, but they are truly ancient! Even GHC 7.4 has unix 2.5, and that's the oldest GHC I have. Do you use this package with GHC 7.0, or did this just come out of the matrix builder?

I've updated the bounds for GHC 8 BTW, everything seems to work.

**Comment by hvr** [comment]
Mostly from the matrix builder; it's perfectly ok to drop support for ancient GHC versions and set lower bounds accordingly...

**Comment by hesselink** [comment]
OK, then I'll leave it for now. If anyone needs this package to support GHC 7.0, let me know, and I'll put in the effort to make it work. It should be relatively simple.
